// packages/react/src/Square.tsx
import { useEffect, useMemo } from "react";
import { Struct } from "utils";

interface SquareProps {
  value: Struct;
  onChange: () => void;
  enableChildrenEvent: boolean;
  time: number;
}

export function Square(props: SquareProps) {
  const { enableChildrenEvent, value, onChange, time } = props;
  const _onChange = useMemo(() => onChange, []);

  useEffect(() => {
    if (!enableChildrenEvent) return;
    const timerId = setInterval(() => {
      _onChange();
    }, time);

    return () => {
      clearInterval(timerId);
    };
  }, [enableChildrenEvent, time, _onChange]);

  return (
    <div
      style={{
        display: "inline-flex",
        width: "40px",
        height: `40px`,
        background: "gray",
        alignItems: "center",
        justifyContent: "center",
        color: "white",
      }}
    >
      {value.count}
    </div>
  );
}

// packages/vue/src/components/Square.vue
<script setup lang="ts">
import { Struct } from 'utils';
const props = defineProps<{ value: Struct }>()
const {
  value,
} = props 
</script>

<template>
  <div class="square">
    {{value.count}}
  </div>
</template>

<style scoped>
.square {
  display: inline-flex;
  width: 40px;
  height: 40px;
  background: gray;
  align-items: center;
  justify-content: center;
  color: white;
}
</style>
